import { Cinzel_Decorative, Raleway, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/compnents/Shared/Navbar";
import ContactInfobar from "@/compnents/Shared/ContactInfobar";

export const cinzel = Cinzel_Decorative({
  subsets: ["latin"],
  weight: ["700"]
})
export const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400","500","600","700"]
})
export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400","500","600","700"]
})



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {/* Navigation bar Start */}
        
          <div className="hidden md:block">
            <ContactInfobar />
          </div>
          <Navbar />
        
        {/* Navigation bar End */}
        {children}
      </body>
    </html>
  );
}
